# Generated by Django 5.1 on 2025-10-01 12:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('requirements', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='maps/main/')),
                ('category', models.CharField(choices=[('apartments', 'Apartments'), ('residential', 'Residential'), ('villa', 'Villa')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter property price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('contemporary', 'Contemporary'), ('bungalow', 'Bungalow'), ('colonial', 'Colonial'), ('cottage', 'Cottage'), ('other', 'Other')], default='modern', max_length=50)),
                ('custom_style', models.CharField(blank=True, help_text='Enter a custom style if not in the list', max_length=100)),
                ('number_of_floors', models.PositiveSmallIntegerField(blank=True, help_text='Optional: Number of floors', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(help_text='Enter number of bathrooms (min 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(help_text='Enter number of bedrooms (min 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('square_meters', models.DecimalField(decimal_places=2, help_text='Enter the size in square meters', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('design_file', models.FileField(blank=True, help_text='Upload design file (PDF or CAD)', null=True, upload_to='maps/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'cad', 'dwg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hero', models.ImageField(blank=True, null=True, upload_to='articles/hero/')),
                ('file', models.FileField(upload_to='articles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('main_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='zenmap.mainmap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainMapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='maps/details/')),
                ('design_file', models.FileField(blank=True, help_text='Upload design file (PDF or CAD)', null=True, upload_to='maps/details/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'cad', 'dwg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='zenmap.mainmap')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
