# Generated by Django 5.1 on 2025-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmap',
            name='code',
            field=models.CharField(default=1, help_text='Enter unique property code (letters, numbers, or symbols)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainmap',
            name='category',
            field=models.CharField(choices=[('apartments', 'Apartments'), ('residential', 'Residential'), ('villa', 'Villa'), ('hotels', 'Hotels'), ('offices', 'Offices'), ('beach_house', 'Beach House'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20),
        ),
    ]
