# Generated by Django 5.1 on 2025-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenmap', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='page',
            field=models.CharField(blank=True, help_text='Page where form was submitted', max_length=50),
        ),
    ]
